### ISSUE TITLE
compile issues due possible refactoring

### ISSUE THREAD

**Issue by armandr** [ftdigdm/EVE-MCU-BRT_AN_025-Example-ESP32#1]
It looks like the code and cmake think the eve_arch_esp32 directory should be in the lib folder and not in the ports directory.

Please let me know if this repo is the proper place for feedback/contrib.

thanks

**Comment by brtchip-gdm** [comment]
Yes indeed, thanks so much for your feedback. 
I've fixed the CMake files and updated references for ESP-IDF v4.4.
Only compilation tested at this point. 
@BRTCHIP-GB: Can you verify functionality on ESP32 then approve related PR if successful?

**Comment by BRTCHIP-GB** [comment]
Your update builds well on release 4.4 of the toolchain.
There is one additional warning
C:/Users/BRT/Documents/GitHub/esp-idf/components/esp_event/include/esp_event_loop.h:2:2: warning: #warning "esp_event_loop.h is deprecated, please include esp_event.h instead" [-Wcpp]
